version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dbenfouzari"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "dbenfouzari"
