name: Native Template

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  init-template:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          path: "dcri-packages"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get pwd
        run: pwd -P

      - name: Get GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE

      - name: Create project
        run: cd $GITHUB_WORKSPACE && npx react-native init NativeProject --template $GITHUB_WORKSPACE/packages/react-native-template-derniercri
        env:
          NODE_ENV: development

      - name: Get Yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE/NativeProject && yarn install --production=false
        env:
          CI: true

      - name: Lint
        run: cd $GITHUB_WORKSPACE/NativeProject && yarn lint

      - name: Test
        run: cd $GITHUB_WORKSPACE/NativeProject && yarn test
